### ISSUE TITLE
Music works inconsistently

### ISSUE THREAD

**Issue by MattiMali** [Lumo-Creations/Harmony-in-the-Wild#343]
Sometimes the background music doesn't play. Going to the snow area made it play again but it played the summer area music instead and played the winter music at the summer area.

**Comment by juttamariia** [comment]
Made a small change in the code, this should work now. Still a chance something is broken, but in theory it should work.

**Comment by MattiMali** [comment]
Still isn't working, there is no music when entering the first time to the overworld and it won't start until going to snow area where it plays summer area's music (and summer area plays winter area's music).

**Comment by juttamariia** [comment]
Located few bugs in the audio code. The music should start playing when you enter Overworld or change the biome - and the tracks shouldn't be reversed any more (forest theme on the forest side and arctic theme on the arctic side).

**Comment by MattiMali** [comment]
Music now works as intended.
